spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: 123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key